# Dependencies
markdown:         redcarpet
#Sass
sass:
    sass_dir: 	  _sass
    style: 	      compressed
# Permalinks
permalink:        pretty
highlighter:      rouge
gems:
  - jekyll-sitemap


# Setup
title:            Institut Des Ongles (spécialiste de l'ongle et de l'esthétique)
keywords: 		  Onglerie, ongles en gels,nail art, ongles, ongles gel, Onglerie, beauté des mains et des pieds, french manucure, manucure, pédicure, épilation, Labège, Toulouse.
description:      Salon esthétique spécialiste de l'ongle &agrave Labège propose la pose d'ongles en gel, vernis permanent, manucure, pédicure, beauté des mains et des pieds, french, réparation d'ongles cassés, décorations sur ongles ainsi que des prestations d'esthétique (épilations...) &agrave quelques minutes de Toulouse. 	
url:              http://www.institutdesongles.fr
paginate:         1
baseurl:          
altlogo:		  Institut des ongles - Onglerie, beauté des mains et de pieds, salon esthétique &agrave; Labège (proche de Toulouse).
tel:			  06 71 64 93 93
author:
  name:           Emmanuel Vinas
  url:            https://twitter.com/EmmanuelVinas
  email:          vinas.emmanuel@gmail.com
promo:		      true

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/EmmanuelVinas/ido
