# Dependencies
markdown:         redcarpet
#Sass
sass:
    sass_dir: 	  _sass
    style: 	      compressed
# Permalinks
permalink:        pretty
highlighter:      rouge
gems:
  - jekyll-sitemap

# Setup
title:            Institut Des Ongles & Beauté - Onglerie, épilations,  soins du visage et du corps.
keywords: 		    Onglerie, salon esthétique, épilations, soins du visage, soin du corps, Hammam, manucure, pédicure, beauté des mains, beauté des pieds, épilations cire, épilations caramel, soins du visage, nail art
description:      Salon esthétique spécialiste en onglerie vous propose des poses de gels et vernis, des épilations à la cire, au caramel et au fil et les soins du visage Maria Galland &agrave Toulouse vous propose des prestations de qualité dans un environnement idéal pour se détendre.
url:              http://www.institutdesongles.fr
baseurl:
altlogo:		      Institut des ongles & Beauté - Onglerie, Epilations et soins du visage, salon esthétique &agrave; Toulouse.
tel:			        09 87 59 75 25
author:
  name:           Emmanuel Vinas
  url:            https://twitter.com/EmmanuelVinas
  email:          vinas.emmanuel@gmail.com
promo:		        false

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/EmmanuelVinas/ido
