baseURL: https://www.institutdesongles.fr/
languageCode: fr-FR
title: Institut des Ongles & beauté Toulouse  
theme: hugo-ido

params:
  keywords:  Onglerie, salon esthétique, épilations, soins du visage, soin du corps, Hammam, manucure, pédicure, beauté des mains, beauté des pieds, épilations cire, épilations caramel, soins du visage, nail art
  description: Salon esthétique spécialiste en onglerie vous propose des poses de gels et vernis, des épilations à la cire, au caramel et au fil et les soins du visage Maria Galland &agrave Toulouse vous propose des prestations de qualité dans un environnement idéal pour se détendre.
  font:
    name: "Open Sans"
    sizes: [400,600]
  home:
    section1-tiles:
    - title: La qualité de nos soins
      icon: icon-check
    - title: Les produits haut de gamme
      icon: icon-check
    - title: La satisfaction de nos client(e)s
      icon: icon-check  
  
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Soin du Visage
    url: /visage
  - title: Epilation
    url: /epilation
  - title: Corps
    url: /corps
    # sublinks:
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
  - title: Ongles
    url: /ongles
  - title: Contact
    url: /contact
    contact: true
